# Generated by Django 5.0.3 on 2024-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_category_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='names',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surnames',
        ),
        migrations.AddField(
            model_name='client',
            name='Cer',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='Key',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='apellidoM',
            field=models.CharField(default='exit', max_length=150, verbose_name='Apellido Materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='apellidoP',
            field=models.CharField(default='exit', max_length=150, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='calle',
            field=models.CharField(default='exit', max_length=150, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='codigoPostal',
            field=models.CharField(default='exit', max_length=150, verbose_name='Codigo Postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='colonia',
            field=models.CharField(default='exit', max_length=150, verbose_name='Colonia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='curp',
            field=models.CharField(default='exit', max_length=18, verbose_name='CURP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='exit', max_length=150, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.CharField(default='exit', max_length=150, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='localidad',
            field=models.CharField(default='exit', max_length=150, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='municipio',
            field=models.CharField(default='exit', max_length=150, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='numeroExterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero Exterior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='numeroInterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero Interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='pais',
            field=models.CharField(default='exit', max_length=150, verbose_name='pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='passphrase',
            field=models.CharField(default='exit', max_length=150, verbose_name='Passphrase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(default='exit', max_length=13, verbose_name='RFC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telefono',
            field=models.PositiveIntegerField(default=0, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tipoCliente',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino')], default='o', help_text='Book availability', max_length=20),
        ),
    ]
