# Generated by Django 5.0.3 on 2024-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_names_client_nombre_remove_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tipoReceptor',
            field=models.CharField(blank=True, choices=[('moral', 'Persona Moral'), ('fisica', 'Persona Fisica'), ('extranjero', 'Extranjero')], default='o', help_text='Book availability', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipoCliente',
            field=models.CharField(blank=True, choices=[('o', 'OnDemant'), ('p', 'Prepago')], default='o', help_text='Book availability', max_length=20),
        ),
    ]
