# Generated by Django 5.0.3 on 2024-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_client_tiporeceptor_alter_client_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Cer',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='Key',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='calle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=150, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='curp',
            field=models.CharField(blank=True, max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numeroExterior',
            field=models.PositiveIntegerField(blank=True, verbose_name='Numero Exterior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numeroInterior',
            field=models.PositiveIntegerField(blank=True, verbose_name='Numero Interior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passphrase',
            field=models.CharField(blank=True, max_length=150, verbose_name='Passphrase'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipoReceptor',
            field=models.CharField(blank=True, choices=[('moral', 'Persona Moral'), ('fisica', 'Persona Fisica'), ('extranjero', 'Extranjero')], default='moral', help_text='Book availability', max_length=15),
        ),
    ]
