# Generated by Django 5.0.3 on 2024-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_client_cer_alter_client_key_alter_client_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numeroExterior',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Exterior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numeroInterior',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Interior'),
        ),
    ]
