# Generated by Django 5.0.3 on 2024-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_client_numeroexterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
