# Generated by Django 5.0.3 on 2024-05-29 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_client_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tipoCliente',
            field=models.CharField(blank=True, choices=[('o', 'OnDemant'), ('p', 'Prepago')], default='o', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipoReceptor',
            field=models.CharField(blank=True, choices=[('moral', 'Persona Moral'), ('fisica', 'Persona Fisica'), ('extranjero', 'Extranjero')], default='moral', max_length=15),
        ),
        migrations.CreateModel(
            name='User_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timbres', models.IntegerField(default=20, verbose_name='Timbres')),
                ('estatus', models.CharField(choices=[('ac', 'Activo'), ('in', 'Inactivo')], default='ac')),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.client')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
    ]
