# Generated by Django 5.0.3 on 2024-05-29 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_client_tipocliente_alter_client_tiporeceptor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_cliente',
            options={'ordering': ['id'], 'verbose_name': 'User_Cliente', 'verbose_name_plural': 'User_Clientes'},
        ),
        migrations.AlterField(
            model_name='user_cliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client'),
        ),
    ]
