# Generated by Django 5.0.3 on 2024-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_user_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cliente',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo'),
        ),
    ]
